# Generated by Django 6.0 on 2026-01-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('name', models.CharField(default='Willis Ogecha', max_length=100)),
                ('title', models.CharField(default='Machine Learning & Software Engineer', max_length=200)),
                ('bio', models.TextField(default='I build intelligent, data-driven solutions using Machine Learning, Computer Vision, and modern backend technologies.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
