# Generated by Django 6.0 on 2026-01-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Languages', 'Programming Languages'), ('Frameworks', 'Frameworks & Libraries'), ('Tools', 'Tools & Platforms'), ('Databases', 'Databases'), ('Other', 'Other')], default='Other', max_length=50)),
                ('proficiency', models.IntegerField(default=50, help_text='Proficiency level (0-100)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
