# Generated by Django 6.0 on 2026-01-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesettings_email_sitesettings_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume (PDF)', null=True, upload_to='cv/'),
        ),
    ]
