# Generated by Django 6.0 on 2026-01-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('credential_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('skills', models.TextField(default='', help_text='Comma-separated skills')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
    ]
